import math
from typing import List

# A list of phrases that suggest the LLM failed to find the answer in the context
HEDGING_PHRASES = [
    "i don't have enough information",
    "i do not have enough information",
    "not contained within the provided context",
    "cannot answer based on the provided",
    "the provided documents do not",
    "there is no information",
    "i don't know based on the provided",
    "does not mention"
]

def compute_confidence(retrieval_scores: List[float], llm_answer: str) -> float:
    """
    Computes a simple, defensible confidence score (0.0 to 1.0) for the final response.
    
    The score is calculated by:
    1. Normalizing the top retrieval score (assumes scores where higher is better, e.g. CrossEncoder logits).
    2. Applying a heavy penalty if the LLM's answer contains known hedging language.
       
    Args:
        retrieval_scores: A list of float scores from the reranker/retriever.
        llm_answer: The final text string generated by the LLM.
        
    Returns:
        float: A confidence score between 0.0 and 1.0.
    """
    if not retrieval_scores:
        return 0.0
        
    # 1. Normalize top retrieval score
    # Assuming these are CrossEncoder logits (which can range roughly from -10 to 10).
    # We use a standard sigmoid function to smoothly squash the logit into a 0-1 probability.
    top_score = max(retrieval_scores)
    try:
        base_confidence = 1 / (1 + math.exp(-top_score))
    except OverflowError:
        # Handle extreme negative scores
        base_confidence = 0.0
        
    # 2. Penalize for hedging language
    answer_lower = llm_answer.lower()
    
    # Check if any of our predefined hedging phrases appear in the LLM's response
    is_hedging = any(phrase in answer_lower for phrase in HEDGING_PHRASES)
    
    if is_hedging:
        # If the LLM explicitly states it doesn't know, the system confidence should plummet,
        # regardless of how highly the cross-encoder ranked the chunks.
        return round(base_confidence * 0.1, 4)
        
    return round(base_confidence, 4)
